version: '3'
services:
  breweryservice:
    image: utlavenkat/brewery
    ports:
      - 8081:8081
    restart: always
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8081/brewery/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 4
    deploy:
      replicas: 3